### ISSUE TITLE
Ignoring short goal - duration

### ISSUE THREAD

**Issue by danpillay87** [swehner/foos#33]
hello - when running through my pi i'm constantly getting "ignoring short goal - duration X" being outputted to the console even when event_debug is not enabled as a module - is this expected activity - any reason this would be constantly logging that people might be aware of?

Thanks

**Comment by swehner** [comment]
Hey,

Are you actually using the arduino for the goal inputs? This warning is only printed if a goal_event is received and it carries a duration amount that is too small.
So you'd have to check who is actually generating these goal events..
This is printed by the score plugin - not the event_debug plugin.
I'd try to see what is generating these goal events and what their format is.
If you're using an Arduino, do check the serial output in the serial monitor in Arduino IDE and verify what they format of the goal events is.

**Comment by danpillay87** [comment]
Seems to be generated by yellow team with source: serial but I'll keep
digging and see if anything else uncovers itself in the logs! Thanks

**Comment by swehner** [comment]
Hey - if you're still having with issues with this, you can post some output from the serial monitor of the arduino IDE while you're using the arduino (pushing buttons, triggering goals) - Maybe I see something weird.
You can also put some print statements before https://github.com/swehner/foos/blob/master/plugins/io_serial.py#L39
to see what you're Arduino is sending.

**Comment by danpillay87** [comment]
thanks - I'm testing this just with arduino IDE and you're right - seems like it's isolated to do with my arduino code - getting a constant output of non-standard characters. Guessing I've compiled the arduino code incorrectly which I'll look into myself but if this has been a problem for anyone else, please feel free to point me in the direction.
[arduino-sketch.txt](https://github.com/swehner/foos/files/428180/arduino-sketch.txt)

**Comment by danpillay87** [comment]
ok that was simple - didn't realise baud rate should be 115200 - with that the serial monitor still outputs constantly:

YG 24 908
YG 24 912
YG 32 892
YG 28 904
YG 28 908
YG 20 904
YG 28 920
YG 16 904
YG 16 920
YG 40 920
YG 28 876
YG 32 904
YG 32 904

That's with just the nano attached at the moment, hence the constant output to the PI & crashing - any ideas welcome, hardware is definitely not my area, though I'm doing my upmost!

**Comment by swehner** [comment]
So, I think I need some more info on what you're using.
First of all, you're running the .ino file from the repository, right?
I understand that you have connected the IR receiver and Emitter, right? If not - if you just plugin the arduino as it is without connecting anything, the input ports might be floating and this could easily produce this behavior...
There is no pull-down configured on those ports so if there's nothing connected it'll be reading either 1 or 0 randomly.

If you have something connected can you send the part numbers (just in case you have a slightly different component).

Does this also happen with the black IR sensor?
 
Check if it's something the IR sensor is receiving - see if it stops if you cover it with your hand or a dark plastic cup or something similar.

**Comment by danpillay87** [comment]
thanks Swehner - I tried both with and without the ir received and emitter set-up - if I comment out the yellow goal only then all is well so I'm guessing it must just be a hardware issue otherwise the black goal would be triggering as well.

 if (goalsEnabled) {
      //processGoal(d, PIN_MASK_YELLOW, &goalY, &goalTimeY, &offTimeY, GOAL_YELLOW_STR);
      processGoal(d, PIN_MASK_BLACK,  &goalB, &goalTimeB, &offTimeB, GOAL_BLACK_STR);
    }

I'm going to attempt switching the yellow goal pin from pin 10 to pin 12 to see if that resolves the issue.

**Comment by danpillay87** [comment]
this seems to have done the trick thankfully in case anyone has any issues.
