### ISSUE TITLE
Button Pins

### ISSUE THREAD

**Issue by ErnieTheTech** [swehner/foos#36]
Hey guys, sorry I have been away. I work for a University and since we started classes last month I have been slammed. 

I started up my project again this week and made a button box prototype. LED's work great but I cant seem to figure out the button inputs. If I do them one by one it seems to map this:

D2=-Yellow
D3=+Yellow
D4=-Black
D5=+Black
D6=Replay?

When I put them all connected at once it doesnt seem to work. Buttons start to open menus that I cannot control. Is there something I am doing wrong? Where do I edit the config for button inputs?

Thanks again
![14424150_652409691576582_1028303617_o](https://cloud.githubusercontent.com/assets/20694528/18760667/05039510-80d0-11e6-8b20-c057e4b00c03.jpg)
![14453925_652409658243252_986464525_o](https://cloud.githubusercontent.com/assets/20694528/18760684/137d6256-80d0-11e6-83e8-94ccb657fb1b.jpg)

**Comment by Essilor84** [comment]
How you fix that Problem?
