### ISSUE TITLE
"Permission Denied" When running ./check on Test Replays

### ISSUE THREAD

**Issue by cloworm** [swehner/foos#37]
Making a Foosball Table in our fab lab and my colleague is trying to use your project.

Exact error is:

`Running camera...

./check: line 122: 2284 Terminated video/run-camera.sh
video/replay.sh: 12: video/replay.sh: video/player/player: Permission denied`

We tried running the command with sudo and checking the permissions, and we are having trouble solving the issue.

**Comment by swehner** [comment]
So, I understand you're running this on the raspberry pi with the pi user.
Did you build the player using: `pushd video/player; make && popd`?
Can you include an output of: `ls -al video/player`?

**Comment by cloworm** [comment]
A player was never built manually, no. We looked through the readme but couldn't find any reference to that command - we only saw it referenced in the check file

the output is:
`pi@raspberrypi:~/foos-master $ ls -al video/player
total 220
drwxrwxrwx 3 pi pi 4096 Sep 15 15:07 .
drwxrwxrwx 3 pi pi 4096 Sep 14 15:10 ..
-rwxrwxrwx 1 pi pi 923 Sep 14 15:10 Makefile
drwxrwxrwx 2 pi pi 4096 Sep 15 15:07 player
-rwxrwxrwx 1 pi pi 8622 Sep 14 15:10 video.c
-rwxrwxrwx 1 pi pi 195352 Sep 15 14:50 video.o`

**Comment by swehner** [comment]
Hi,

You're right - that step is missig in the Readme. I'll add it - thanks for pointing it out.
So, it looks like kind of weird - becaue video/player seems to be a directory in your case instead of the compiled executable.
Can you go and delete that directory and compile it again?

```
cd video/player
rm -rf player
make
```
It looks like something weird happened there...
This is what it should look like:

```
pi@raspberrypi:~/foos $ ls -al video/player/
total 408
drwxr-xr-x 2 pi pi   4096 Nov 11 15:44 .
drwxr-xr-x 3 pi pi   4096 Aug 27 14:06 ..
-rw-r--r-- 1 pi pi    923 Aug 27 14:06 Makefile
-rwxr-xr-x 1 pi pi 194588 Nov 11 15:42 player
-rw-r--r-- 1 pi pi   8622 Aug 27 14:06 video.c
-rw-r--r-- 1 pi pi 195636 Nov 11 15:38 video.o
```

**Comment by cloworm** [comment]
We tried following your instructions and get this error after inputting the `make` command:

```
pi@raspberrypi:~/foos-master/video/player $ make
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g3 -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -c video.c -o video.o -Wno-deprecated-declarations
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g3 -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -L/opt/vc/lib/ -lGLESv2 -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm -L/opt/vc/src/hello_pi/libs/ilclient -L/opt/vc/src/hello_pi/libs/vgfont -o player video.o -lilclient
/usr/bin/ld: cannot find -lilclient
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'player' failed
make: *** [player] Error 1
```

```
pi@raspberrypi:~/foos-master/video/player $ ../.././check 
Checking environment...

* Binary deps:
[ OK] play (needed for sound) found
[ OK] avconv (needed for upload) found
[ OK] cec-client (needed for standby) found
[ OK] python3 (needed for foos) found
[ OK] pip3 (needed for foos) found

* RaspberryPi specific deps:
[ OK] /opt/vc/bin/raspivid (needed for camera)
[ERR] video/player/player (needed for replay) not found
====> Try: pushd video/player; make && popd 

* Replay path:
/usr/bin/python3: Error while finding spec for 'foos.config_getter' (<class 'ImportError'>: No module named 'foos')
[ERR] Replay path should be on a tmpfs filesystem instead of ext2/ext3
[ OK] is writable

* GPU settings:
[ OK] GPU memory set to 192

* evdev input:
[ OK] /dev/input seems readable io_evdev_keyboard should work

* Python deps
[   ] Can't check python3 deps for the moment - if you have issues:
====> Try: pip3 install -r requirements 

* Test Replays - press Y to test N to skip

* Finished!

pi@raspberrypi:~/foos-master $ pushd video/player; make && popd
~/foos-master/video/player ~/foos-master
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g3 -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -L/opt/vc/lib/ -lGLESv2 -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm -L/opt/vc/src/hello_pi/libs/ilclient -L/opt/vc/src/hello_pi/libs/vgfont -o player video.o -lilclient
/usr/bin/ld: cannot find -lilclient
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'player' failed
make: *** [player] Error 1
```

**Comment by swehner** [comment]
Ok, so it looks like you have the examples in /opt/vc/src/hello_pi (on my raspbian it's the package libraspberrypi-doc, in cas you need to install it).
Do run:
```
pi@raspberrypi:/opt/vc/src/hello_pi $ ./rebuild.sh 
```
That should hopefully do the trick and generate the missing libraries.
Afterwards compiling the player should work.
Let me know if that did the trick - I'll include it in the check script.

**Comment by JPrevost** [comment]
FYI. I ran into the same problem and running `rebuild.sh` does let me get past it. Thanks!

**Comment by cloworm** [comment]
Thanks, it did the trick for me also!

**Comment by illing2005** [comment]
Thanks!
I had the same problem. Runnig `rebuild.sh` did do the trick.
I think this should be added to the troubleshoot section.

**Comment by swehner** [comment]
Was this with the lates version of the code? The newer versions have a custom player exec compiled in video/player - so they shouldn't be using the demo player from the rpi firmware.
If the player doens't exist "check" tells you how to compile it. Hope that helps.

**Comment by cschaffner** [comment]
I just had exactly the same error:
```
pi@raspberrypi:~/foos-master $ pushd video/player; make && popd
~/foos-master/video/player ~/foos-master
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g3 -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -L/opt/vc/lib/ -lGLESv2 -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm -L/opt/vc/src/hello_pi/libs/ilclient -L/opt/vc/src/hello_pi/libs/vgfont -o player video.o -lilclient
/usr/bin/ld: cannot find -lilclient
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'player' failed
make: *** [player] Error 1
```
 on a new Pi with the latest Raspbian software. Running `rebuild.sh` as above has then allowed me to compile the player.

**Comment by swehner** [comment]
Ah ok! That makes sense, that it is due to the libraries - i thought it was because of the player itself. Thanks for reporting! I'll see how to include it!
