### ISSUE TITLE
Goal ocurring when arduino starts

### ISSUE THREAD

**Issue by swehner** [swehner/foos#4]
Everytime the arduino starts or the serial connection is reset (which reboots the arduino) a fake goal appears.
Maybe we should wait a bit when registering the interrupt handlers to avoid fake goals.

**Comment by swehner** [comment]
Commit b3a6bfd seemed to fix this for the boot because now the IR emitter is set up some time before the interrupt handlers are registered, but when a soft-reset from the serial port happens this still seems to be an issue (handlers remain registered and the IR emitters are reset)

**Comment by swehner** [comment]
Fixed in 73b11e2

**Comment by dpaneda** [comment]
OMG thank you for fixing this annoying issue! :dancers: :dancers:
