### ISSUE TITLE
Video Recording

### ISSUE THREAD

**Issue by danpillay87** [swehner/foos#41]
Hi! I've updated to latest foos ( much easier install and great documentation thanks!) Everything is sorted other than the recording, which seems to be stuck on a recorded image rather than overwriting each time a goal is scored. I'm getting the chunks from the initial test I believe. Can't seem to see any error logging for this though as I suppose the play functionality is working as expected?

**Comment by swehner** [comment]
Hi,

Are you sure the camera plugin is running? The camera plugin is not in the default list from config_base.py, so you need to make sure to add it.
Check if raspivid is running and with what parameters (ps ax | grep raspivid) - video chunks should be written to /dev/shm/replay/fragments/out%04d.h264 - the path is configured in the replay_path variable.

When you run the "check" script does the replay work there?
It should use the same configuration as foos.py when it's running - so if it works there it should work in the game...
It should also check if the directory is writeable for the current user, but you can double check.

The replay files are in /dev/shm/replay/replay_short.h264 and replay_long.h264 - check if they are being updated when a goal is scored.

In case it still doesn't work you can add this line in foos/process.py to see what argument are being used when the replay generation scripts are called: 

```
diff --git a/foos/process.py b/foos/process.py
index f8894e0..59ece73 100644
--- a/foos/process.py
+++ b/foos/process.py
@@ -5,6 +5,7 @@ logger = logging.getLogger(__name__)
 
 def call_and_log(*args, **kwargs):
     """Run process, gather output and write to log"""
+    logger.info("Running %s", args)
     p = subprocess.Popen(*args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
     stdout, stderr = p.communicate()
     if len(stdout) > 0:
```

**Comment by danpillay87** [comment]
hey this seemed to only happen on remote ssh and otherwise seems to work
