### ISSUE TITLE
Arduino connection to RPi

### ISSUE THREAD

**Issue by ewoco** [swehner/foos#43]
I might just be missing something, but:

How does the RPi connect to the arduino? Using the standard TX and RX on both?

**Comment by swehner** [comment]
Hey,

The Arduino si connected via a USB cable to the Raspberry Pi (https://github.com/swehner/foos/blob/master/doc/HWSetup.md#raspberry-pi), the same way you'd connect it for programming.
It uses the serial over USB to communicate with the Pi
