### ISSUE TITLE
Crontab / job

### ISSUE THREAD

**Issue by LukeSeinVadder** [swehner/foos#59]
Me again, sorry ;)

I want to make foos as a autostart program, when I put it into a crontab, foos is starting , but the camera is not starting with it. 

```@reboot /usr/bin/python3 /home/pi/foos/foos.py```

Have you got an idea, how I can realize this, that the rasperry automatically starting it. 

BTW, do you really use the V2 Camera, we must go back 2 meters to see the hole table... now we use the 1.3 camera the lense could be nearer to the table.

**Comment by swehner** [comment]
So, you can definitely use the v1 camera... In my previous messages I didn't want to imply that you needed v2 - I just wanted to know which one you were using.
I didn't realize they had different lenses - so whatever works best.

**Comment by swehner** [comment]
Regarding running something on startup you can also try to use rc.local: https://www.raspberrypi.org/documentation/linux/usage/rc-local.md
If the camera isn't running maybe there's some issue with the environment and it doesn't find the required binaries/libraries. Check if something's in the log file in /dev/shm/foos_event.log.
Maybe also running it and redirecting the error and console output to a file might help to see if something's wrong...

**Comment by swehner** [comment]
BTW: here's also some documentation on how the FOV changes depending on the selected camera mode: https://picamera.readthedocs.io/en/release-1.12/fov.html that might be interesting. Maybe you want to play with the parameters to see if it gets better using a different resolution!

**Comment by LukeSeinVadder** [comment]
Happy new year !

Excuse me, that I write back late, but I have little time the last 2 month for this projekt.
After many many problems, now we are finished with this projekt.
The camera now works great und all things are ok. 
The only problem is to start it automatically in the rpi, I made the job with the rc-local, but it still doesnt work. And I forget to check the event.log, I will make this next time , when I have the rpi at home. 

Here are some pictures, how we solve the LCD and camera position with a metal stand and the buttons in the side of the table, enjoy it, and I hope this pictures are an inspiration for other to build this project.

Thanks a lot for your time to help me.

![2](https://user-images.githubusercontent.com/44442661/51032266-a264a900-159f-11e9-98f7-6267ecc2c38e.jpeg)
![image1](https://user-images.githubusercontent.com/44442661/51032267-a264a900-159f-11e9-93c9-9193b9ec8d60.jpeg)
![image3](https://user-images.githubusercontent.com/44442661/51032268-a264a900-159f-11e9-8b9d-791c4499d638.jpeg)
![image4](https://user-images.githubusercontent.com/44442661/51032269-a264a900-159f-11e9-820a-3101856de3e1.jpeg)
![image12](https://user-images.githubusercontent.com/44442661/51032270-a264a900-159f-11e9-8d64-549bbf4a6752.png)
![img_8406](https://user-images.githubusercontent.com/44442661/51032271-a2fd3f80-159f-11e9-9a12-316bc32d495d.JPG)

**Comment by swehner** [comment]
Happy new year to you, too!
That is a pretty awesome build! Thanks for sharing the pictures - would you mind if I post/link them on the project site as your build?

Regarding the rc.local issue: do check the syslog (not sure if something is output there).

**Comment by LukeSeinVadder** [comment]
Hello there, 

it's my honor, you're welcome to link it on the project page. 
When you consider that it's my first project, I've got it all right with your help 😂

Now I have to clone und save the SD - card 😎 , I dont think that I can build it two times. 
So many information and reading internet sites to understand just a little bit, how you build this project. 
It an awesome work !!!

**Comment by jeanmichelbouchard** [comment]
Thanks for the cue! I am implementing that version of raspberry only but the doc is pretty light for it. I will try with that pin for the PWM clock. I think it’s different than what I tried. 

Good night!
Jean-Michel

**Comment by swehner** [comment]
Yes, I know there isn't much doc... If you take some notes I'll be more than happy to add them to the doc here: https://github.com/swehner/foos/blob/master/doc/HWSetup.md#setup-without-an-arduino

Basically you should just need to enable to raspberry plugin and add the config for the pins.
See https://github.com/swehner/foos/blob/master/config.py.sample#L28-L39

The wiring should be pretty much the same as for the arduino...

**Comment by jeanmichelbouchard** [comment]
I have another question. On the wiring diagram there is a capacitor on each receiver and also a 100 ohms resistor but they aren’t on the shopping list. Are they necessary?

Jean-Michel

**Comment by jeanmichelbouchard** [comment]
My Goal detectors work! I will send you a schematic for Pi-only version when finished. I now have a weird problem with my buttons. The program only detects one out of three or four pushs. With a custom program the button is detected correctly. Did you have such a problem? I am searching for an explanation. Also, is there an easy way to not display the background to see the console while running?

Thanks for your answers, really appreciated :)
Jean-Michel

**Comment by swehner** [comment]
To keep having the console I'd recommend connecting over ssh to your RaspberryPi and running foos from the ssh terminal you're using. If you don't want/can't do this you can start commenting out the code that creates the background, but that'll be a bit trickier:
* https://github.com/swehner/foos/blob/master/foos/ui/ui.py#L346-L354
* https://github.com/swehner/foos/blob/master/foos/ui/ui.py#L499

Re: the buttons - what custom program are you using? Are you using the same code used as here? 
https://github.com/swehner/foos/blob/master/plugins/io_raspberry.py#L20
Does it miss short button presses (maybe play with the debounce time)?

**Comment by jeanmichelbouchard** [comment]
Got it, I reduced the debounce time and it solved the problem pretty well. 

Jean-Michel

**Comment by swehner** [comment]
Nice! I've added some documentation on how to start foos from rc.local that @LukeSeinVadder asked about here: https://github.com/swehner/foos/blob/master/doc/Installation.md#start-foos-on-boot
That worked fine for a clean installation from scratch.
Let me know if that works for you so I can close this issue! Thanks!

**Comment by LukeSeinVadder** [comment]
Hi back again , 

```20:36:30    INFO __main__ - Foos v20160814 starting
20:36:30   ERROR foos.process - /bin/sh: 1: video/blank_console.sh: not found
20:36:30   ERROR foos.process - video/blank_console.sh blank returned 127
20:36:30    INFO foos.ui.ui - Display 1280x720@25
20:36:34    INFO foos.plugin_handler - Loading plugins {'score', 'sound', 'leds', 'camera', 'menu', 'replay', 'control', 'io_debug', 'game', 'io_serial', 'league'}
20:36:34    INFO plugins.io_serial - Opening /dev/ttyUSB0
```

I cant start the program in the rc.local, this is from the foos event.log. 

The program try to start for 1 second with the foos backround and end it directly.

**Comment by swehner** [comment]
Looks like there's some issue with the path. Are you using the foos.sh in rc.local I've pushed the other day?
I'm asking because this should be running it in the correct path
https://github.com/swehner/foos/commit/35a857fc9761e2ecb7bc992e00a894502845eb39#diff-e9b6b4ecca6a697493e181ae3f455572

If this is the only problem (which I doubt) you could also disable it by adding `blank_console = False` to your config.py.

**Comment by jeanmichelbouchard** [comment]
Hi!
Did you get my question about how to create players and launch the tournament in the tournament app?

Here is some code I changed to parametrize and randomize the winner strings that appear when a goal is made. You can put the strings you want in the config and each time a random one is displayed. 

In ui.py : 

class WinnerString:
    def __init__(self, shader, teams=["yellow", "black"]):
        font = img("Ubuntu-B.ttf")
        duration = 5
        drop_duration = 0.2
        self.shapes = {}
        for i, team in enumerate(teams):
            self.shapes[team] = []
            for j, winnerString in enumerate(config.winner_strings):
#                print(winnerString.format(utils.teamName(team).capitalize())) #debug
                s = FixedOutlineString(font, winnerString.format(utils.teamName(team).capitalize()), outline_size=2, font_size=180, shader=shader)
                s = Move(Disappear(s.sprite, duration=duration), duration=drop_duration)
                self.shapes[team].append(s)

    def draw(self):
        for team, s in self.shapes.items():
            for shape in s:
                shape.draw()

    def show_winner(self, team):
        for t, s in self.shapes.items():
            if team == t:
                shape = random.choice(s)
                shape.position(0, 650, 40)
                shape.moveTo((0, 330, 40), (1, 1, 1))
                shape.show()
            else:
                for shape in s:
                    shape.hide()

In config.py :

# Winner strings
winner_strings = ["Victoire des {}!","Des kings les {}!","Les {} déchirent!","Trop forts les {}!","Faites place aux {}!","You rock !!!"]

-- 
Jean-Michel Bouchard, ing.
(418) 956-FIJI (3454)
---------------------------------------------------

**Comment by swehner** [comment]
The foos-tournament is written by a friend with whom we built the whole
setup. I'm not too familiar with the commands of setting up a league -
maybe you can open an issue in the github project and ask there...

Choosing different winner strings might be ineresting!
You can make a pull request so we can review the changes.
Please keep in mind that the default data should always be in english.
Although we should look into internationalizing it and supporting other
languages...

**Comment by LukeSeinVadder** [comment]
Hello there,
Yesterday I made a complete new installation of a new SD card and lo and behold it all works.
The startup works wonderfully.
Thus, the topic can now be closed here.
Thank you again.

**Comment by swehner** [comment]
Awesome. Closing the issue!
