### ISSUE TITLE
How to show longer replays

### ISSUE THREAD

**Issue by jeanmichelbouchard** [swehner/foos#63]
Hi, how can I have longer replays? I have searched the config and code and don’t see how to change that.
Thanks a lot!
Jean-Michel

**Comment by jeanmichelbouchard** [comment]
Ok I found out, adding short_chunks = 20 to the config.py, 10 is the default. That doubles the replay length.

**Comment by swehner** [comment]
Yes, you're right. you can control the number of chunks that is used for replay.
These are the chunk settings for raspivid: https://github.com/swehner/foos/blob/master/config_base.py#L40
This configures how long the chunks are and how many are stored - see https://elinux.org/Rpi_Camera_Module#RaspiVid for example for doc on the options.
I don't think the duration in ms of each chunk was not too accurate...

Every time a replay is generated it stores both a short file (short_chunks) and a longer file (long_chunks).
A manual request triggers replaying the long file and a goal triggers the shorter (we found it to be a bit boring to have longer replays for goals).
