### ISSUE TITLE
38khz pwm only to+  IR led or to + ir receiver too?

### ISSUE THREAD

**Issue by Essilor84** [swehner/foos#64]
Hi , i want to Build raspberry only.
How i connect the 38khz Signal? 
Pwm——> resistor—->+ led i think Thats right?
I have to use the pwm for Receiver too? 
Or i only use 5v —->resistor——>+ ir receiver?
Sry for na Bad english, its my First rapsberry project But i want to tune my Kicker :)

**Comment by jeanmichelbouchard** [comment]
Hi Essilor84, you can check on my fork of the project I have provided a schéma for the Pi-only setup. I didn’t do a pull request yet. Let me know if it suits your need. 
https://github.com/jeanmichelbouchard/foos/blob/master/doc/HWSetup.md

**Comment by swehner** [comment]
@jeanmichelbouchard looks nice! i'd appreciate a pull request :)
Q1 is a transistor to avoid driving the emitter leds directly from the raspberry pi (or the arduino). There's a limit on how many current a pin can provide - so you basically use the transistor to turn the leds connected to the power supply on and off at the frequency provided by the pwm pin.

**Comment by Essilor84** [comment]
i Test it on a breadboard . It works very well ! Thanks for your help.
How i can change the background picture?
Greetings jochen

**Comment by swehner** [comment]
Nice! You can put images in img/bg and they should be loaded and rotated automatically.
Folder for bg images: https://github.com/swehner/foos/tree/master/img/bg
Config for switching bg: https://github.com/swehner/foos/blob/master/config_base.py#L7
You can override this value in your config.py if you want to change the time it takes to rotate...
