### ISSUE TITLE
How i can change the gamemode on Start?

### ISSUE THREAD

**Issue by Essilor84** [swehner/foos#66]
Hi, How i can change the gamemode who Starts First After reboot?
Greets

**Comment by swehner** [comment]
Each plugin can store its state implementing the load and save handlers.
The game plugin saves and recovers at shutdown/boot here: https://github.com/swehner/foos/blob/master/plugins/game.py#L137-L142

But I don't think there's an easy way to set the mode chosen at startup if there's no save file.
Easiest way would be to provide a .status file with the selected mode...
Would that solve your use case?
