### ISSUE TITLE
Button Pins dont work....

### ISSUE THREAD

**Issue by Essilor84** [swehner/foos#67]
Hi, if i use smd push Buttons i works well.
Now i want to use LED-Arcade push Buttons.
I Check Every Connection with multimeter, its Looks perfect nur the Pins works only sporadically.
![image](https://user-images.githubusercontent.com/48887128/57644332-32e9df00-75bc-11e9-8ec4-ec8bded7d273.jpg)
I use raspi only Version.
WHO has a Idea?
Thanks and Greets ,Jochen

**Comment by Essilor84** [comment]
If i Hammer the buttons (2-3 Times per Second ) its works...??

**Comment by Essilor84** [comment]
its possible to log something? Whats Happen Wehen i Push the Button?

**Comment by Essilor84** [comment]
i think there is a Problem with debounce:/ if i solder microswitches all works....

**Comment by swehner** [comment]
It's hard to tell... you don't happen to have something like an oscilloscope to see what the switch is actually doing, right?
I would try to put a print statement here https://github.com/swehner/foos/blob/master/plugins/io_raspberry.py#L26 to see how often this callback function is actually triggered.
You can try to set bouncetime to 0 see how often it's actually triggering (maybe it's constantly).
Maybe you can try the suggestions to add a capacitor around the switch like it's suggested here: https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/

**Comment by Essilor84** [comment]
i Play with debounce Time = no change.
I try Hardware Solution (capacitator)= no change.
Now i solder a not quick but very,very Dirty Solution ;).
It works :)!!
![Uploading C86A6D7A-A504-4F05-A4E1-7DE22633C1E3.jpeg…]()
