### ISSUE TITLE
Goals keep registering as long as LED is pointing at receiver, and stops when it is blocked

### ISSUE THREAD

**Issue by masseyjeremy** [swehner/foos#72]
Hi, so i wired up the schematic for the pi-only version, using a PNP transistor. It is working!! However, rather than registering a goal when the sensor is blocked, it is registering goals when the sensor is not blocked. As long as the IR is pointed at the sensor, it keeps adding more and more goals. As soon as I block it with my hand, it stops adding goals. So it seems exactly opposite of what I need it to do. Is there a setting somewhere to fix this and reverse the logic? Or maybe I have this wired up wrong somewhere?
Edit: Some additional info: I am using Vishay TSHF6410 IR LEDs and Vishay TSSP58038 IR Receivers, as mentioned in the BOM list. So far I have only wired up one receiver & led for my testing, assuming that both dont need wired up to do this test.
Edit2: Now that I played around with it more, actually it seems to be working correctly as long as I have the LED almost touching the sensor. I think when i had it further away maybe the led was so dim that it was detecting it as breaking the IR barrier. So....I am new to this, but learning. And I went with the 330ohm resistor on the 5v line as the schematic shows. By my calculations (again, i could be wrong!) that is way too much resistance. The tech sheet on the LED says it has 1.6voltage drop (forward voltage) and I think if I'm reading it right, I need to supply 100mah to this LED.  So using ohms law of V = I X R. To get the V...5v - 1.6 = 3.4 . So 3.4 V = 100mah X Resistance. So....3.4 / .1 = 34. So I think I need a 34ohm resistor, rather than 330. Does my math sound right? I also wonder if I should have gotten a different LED. The TSHF6410 is 890nm. And the IR receiver's peak wavelength is 940nm. I can use a TV remote from across the room and the sensor detects it and counts it as a goal, but i just tried a 100 ohm resistor (lowest i currently have) on the IR LED and the sensor still cant detect the LED if its further than maybe 6-8 inches away.

**Comment by swehner** [comment]
Hey,

Sure - your calculation seems correct, you'd need a lower resistor to drive the LED at that current.
I think the distance we had between the LED and the receiver was smaller - something around 4-5 inches.
I'll update the resistor values, cause you are right in that they are definitely too high. Not sure if we ended up changing them in or installation and I just failed to update the spec.
Thanks for pointing it out.
Regarding the wavelengths of the IR Led and receiver, I know they don't match exactly, but we didn't find this to be a problem.
What helped us also was to make sure the beam of the led is restricted (e.g. by putting the led in a hole in one of the walls on the ball pickup chute)

**Comment by masseyjeremy** [comment]
Excellent! I really appreciate the response. Sounds like I'm on the right track. I have a variety pack of resistors coming in tomorrow, so when they come in I'll experiment and see what I can get to work. My testing has just been on a breadboard, and manually pointing the LED towards the receiver. I havnt actually installed in the table yet....I also have a Tornado, with same layout as yours. Really looking forward to getting this working. I'll send you a pic of the setup when its completed.

**Comment by masseyjeremy** [comment]
The resistors came in today. I used a 33ohm, and measured the current going to the LED, and its pretty much exactly 100ma now. But, it did not improve anything. The maximum distance I can have the LED from the IR receiver is about 6 inches. But at that distance it continuously counts goals and does not stop. The only way I can get it to stop is to put the LED about 1 cm from the IR receiver. At that distance if I block the signal, it properly counts goals properly (only when i block the led). And as I mentioned, a TV remote gets picked up from across the room....probably 10 feet or more away. So the IR receiver definitely seems to be working ok. It just doesnt seem to like my LEDs. The only things I can think of: Maybe the 38kHz signal from the Pi is not working properly. I've double checked my wiring to the LED, including trying the transistor the other way around (swapping collector/emitter), but i just cant get this to work right. If you have any ideas, please let me know. I'm not sure what else to try other than buying and trying out different LED's / Receivers. Again, thanks so much for the help and for sharing this code. It will be great when I have it setup

**Comment by masseyjeremy** [comment]
So I think i might have found my problem. I noticed this today when I closed the app: "ERROR - /bin/sh: 1: gpio: not found". Maybe this is preventing the 38khz signal to work on GPIO18 pin? I'm not sure how to fix this. I've done:

- pip3 install RPi.GPIO
- pip3 install wiringPi
- pip3 install gpio

But this did not fix it

**Comment by swehner** [comment]
Hey! Great to hear that this worked - I'll add gpio to the dependencies in the check script (even though it's for the pi only version it should be good to install it anyways.
There are a few posts on the internet around different problems with gpio from rc.local: https://raspberrypi.stackexchange.com/questions/4664/setting-gpio-value-on-boot

E.g. mentions that it's not on the default path and that you'd have to add the full path.
You can try to run foos from rc.local this way:

`PATH=$PATH:/usr/local/bin sudo -u pi /home/pi/foos/foos.sh`

or export the PATH before

```
export PATH=$PATH:/usr/local/bin
sudo -u pi /home/pi/foos/foos.sh
```

If this doesn't work, I think the easiest would be to add a "set -x" to the rc.local and see if you can get some debug output.

**Comment by masseyjeremy** [comment]
So I tried both of these methods of setting the path in the rc.local but it didnt work. I also tried putting the entire path in it (the path that I got when logged in as pi).

But maybe the root of the issue can be fixed through getting the software side of things setup right. Which brings up a new question. I tried connecting a pi camera/ enabled the camera plugin, but when foos booted up, it crashed and said I was missing a module. I installed what it said i was missing (with sudo pip3....seems like it was inotify and one or two other ones) and did this a few times with different modules it said it needed, but in the end i was getting different python errors that were more difficult than just installing a missing component.

This leads me to this question: Is there a build of raspbian lite that you recommend using? I had originally installed the latest of wheezy I think, since I know this code has been around for several years so i figured you may have originally used an older version. I couldnt get python3 to work correctly so i just went to the latest of Jessie. This one worked better, and python3 was working, and i used the "pip3 install -r requirements.txt", but I still had to install a few things manually. I might have this off (not sure I took perfect notes), but I think I had to run these to get things working:

sudo apt-get install libjpeg-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libpng-dev


Anyways, I have a nano coming in today, so I may abandon the pi route and go the arduino route. But I would like to get the camera working and thought that maybe I'm just setting something up wrong that has led to my other issues. Like maybe I should just use Stretch or Buster?

**Comment by swehner** [comment]
I think the latest release I tested it with was stretch...
Did you run the "check" - it does verify a few dependencies.
It also checks the memory split, the pi with camera requires a bit more RAM to run both the 3d acceleration and the camera.
I'd double check that.

**Comment by masseyjeremy** [comment]
Yeah, i ran the check. And it says everything is "OK" except for python deps, where it says: "Can't check python3 deps for the moment". For GPU memory, I gave it 256. I'm going to try to get it working with the nano tonight, and then once done maybe will try switching to stretch to see if things work better there.

**Comment by masseyjeremy** [comment]
So, update! I got the Arduino nano hooked up, and goal scoring is now working perfect. In the few games we've played, it was 100% perfect in goal tracking.

So on the side, i tried setting up a new SD card, using the latest build of Stretch this time. I'm basically starting over under stretch and seeing if I can get the camera to work this time. I followed the instructions exactly, including running the check and also running "pip3 install -r requirements.txt". I still had to manually run these two steps in order for Pillow to install since the Pillow install failed and was complaining of missing required dependencies:
sudo apt-get install libjpeg-dev
sudo apt-get install libpng-dev

So then in the config.py, i enabled the standby plugin and io_serial plugin. Then i started up the foos code. But I'm getting this error below. I'll try to troubleshoot later tonight or tomorrow, but any ideas?
![error](https://user-images.githubusercontent.com/44592295/69262425-7471cd00-0b91-11ea-9d5d-97a9a906a370.png)

**Comment by swehner** [comment]
Great to hear that the Arduino setup worked! I'll see if I can verify the seup for the pi-only version during the weekend.

Regarding the issue during the monkey_patch function. 
This isn't actuallly needed for newer versions of pi3d. Can you try removing/commenting the following line?
https://github.com/swehner/foos/blob/master/foos/ui/ui.py#L301

I think there were some recent changes around the piece of code that I was patching here in the recent 2.34 release that make my horrible paching fail (I shouldn't be patching anyways...)
https://github.com/tipam/pi3d/commit/316d5f65beddb21ed0052a60aecafde20419ecda

If commenting this line doesn't work, I'll suggest downgrading it to pi3d 2.32
There's an issue #70 regarding possible issues on the pi4 that I think were addressed in pi 2.34.
I'll try to double check it this weekend and commit the change to remove the patching function

**Comment by masseyjeremy** [comment]
You are awesome! I probably would not have figured that out. Commenting out that line has everything working now. Video playback is working great, except for the FOV. Its good enough that I would be happy enough with it as is, but for the sake of trying to get it better......

As other people have mentioned, I cant get the whole table in view with camera v2. Almost, but not quite. I tried all the different resolution mode settings as you pointed someone else to (https://picamera.readthedocs.io/en/release-1.12/fov.html). 
![fov_v2](https://user-images.githubusercontent.com/44592295/69299948-e113b880-0bdf-11ea-9b47-843a3197a798.png)

Mode 7,1, and 6 were pretty terrible. Modes 2,3,5 actually gave me the same result, which is interesting because 2 and 3 are the full sensor area (see image above) but its at 4:3 ratio. I wonder if the top and bottom bands are getting cut off because its displaying it at 16:9. Do you happen to know how to maybe make it display the 4:3 video, but inside my 16:9 monitor? Understanding that it would have vertical bands on both sides. If I cant figure it out, i may just see if i can find a v1 camera somewhere.

Thanks again for all your help. We're loving this setup!

**Comment by masseyjeremy** [comment]
As an update, in the end, v2 of the camera actually had a better field of view. I think the difference was that you have your v1 camera a little further away from the table, whereas mine is closer. Anyway, I cant get the goalies on either side in the camera view, but thats ok. Good enough. Overall we're super happy with the setup. Thank you for all your help in getting this working! And heres a few photos of the completed project. We also installed a red button on the side of the monitor box to turn the pi on and off. And the table plugs into the wall with just a single network cable. All other cables are hidden. You can close this ticket, but I just wanted to give the final update with these pics.  Thanks again!!!
![foos1](https://user-images.githubusercontent.com/44592295/69561740-e4aa9500-0f7b-11ea-8c72-1871bb729a83.png)
![foos2](https://user-images.githubusercontent.com/44592295/69561752-eb390c80-0f7b-11ea-9c33-f1676502b7f5.png)
![foos3](https://user-images.githubusercontent.com/44592295/69561755-ed02d000-0f7b-11ea-831f-115d4f792963.png)
![foos4](https://user-images.githubusercontent.com/44592295/69561761-eecc9380-0f7b-11ea-98b7-990143357236.png)

**Comment by swehner** [comment]
That looks awesome! Thanks for sending in the pictures - I should actually add a gallery with pictures of other builds :D
Good that the camera works out of you, btw: I like the LEGO touch to it :D ... and the fact that you managed to hide all the cables!

Re camera: maybe some of the cheap fisheye attachment for cellphones might work https://www.aliexpress.com/w/wholesale-fisheye-lens.html ? Unfortunately I never got around to trying it...
Thanks again for letting me know how it turned out! Hope you enjoy it!
