### ISSUE TITLE
Problem mit der GUI (RPi only Setup)

### ISSUE THREAD

**Issue by dpgoerlich** [swehner/foos#84]
ich habe leider ein Problem mit dem Starten der GUI deines Instant Replay System. Ich benutze einen Raspberry 2. Die GUI kommt beim Start des Raspberry kurz und ist dann wieder weg. Ich benutze die Variante ohne Arduino. Beim Manuell starten kommt folgender Fehler:

   INFO - Foos v20160814 starting
   INFO - Blank console
   INFO - Display 640x480@25
glGetError 0x500
   INFO - Loading plugins {'league', 'control', 'io_evdev_keyboard', 'score', 'io_debug', 'game', 'sound', 'leds', 'replay', 'io_raspberry', 'menu', 'camera'}
WARNING - Can't find any keyboards to read from - maybe you need permissions
Traceback (most recent call last):
  File "foos.py", line 50, in <module>
    PluginHandler(bus)
  File "/home/pi/workspaces/foos/foos/plugin_handler.py", line 16, in __init__
    self.load(bus)
  File "/home/pi/workspaces/foos/foos/plugin_handler.py", line 24, in load
    p = module.Plugin(bus)
  File "/home/pi/workspaces/foos/plugins/io_raspberry.py", line 91, in __init__
    self.goal_detector_black = GoalDetector(bus, self.goal_pin_black, "black")
  File "/home/pi/workspaces/foos/plugins/io_raspberry.py", line 47, in __init__
    GPIO.add_event_detect(self.pin, GPIO.FALLING, callback=self.on_goal, bouncetime=10)
RuntimeError: Failed to add edge detection

Hat jemand eine Idee woran das liegen kann ?

LG

**Comment by timomanson** [comment]
Hi ,

 

sieht für mich danach aus als hättest du entweder die GPIO´s nicht an oder evtl. im Konfigurations menue den Eindrahtbus eingeschaltet ….

Wäre meine Idee hatte nen ähnlichen Fehler - 

Welches Betriebssystem nutzt du ?

Hast du die  WiringPi aufgespielt ?

 

 

MFG

 

Timo 

 

Von: Daniel Görlich ***@***.***> 
Gesendet: Dienstag, 13. April 2021 14:34
An: swehner/foos ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [swehner/foos] Problem mit der GUI (RPi only Setup) (#84)

 

ich habe leider ein Problem mit dem Starten der GUI deines Instant Replay System. Ich benutze einen Raspberry 2. Die GUI kommt beim Start des Raspberry kurz und ist dann wieder weg. Ich benutze die Variante ohne Arduino. Beim Manuell starten kommt folgender Fehler:

INFO - Foos v20160814 starting
INFO - Blank console
INFO - Display ***@***.***
glGetError 0x500
INFO - Loading plugins {'league', 'control', 'io_evdev_keyboard', 'score', 'io_debug', 'game', 'sound', 'leds', 'replay', 'io_raspberry', 'menu', 'camera'}
WARNING - Can't find any keyboards to read from - maybe you need permissions
Traceback (most recent call last):
File "foos.py", line 50, in 
PluginHandler(bus)
File "/home/pi/workspaces/foos/foos/plugin_handler.py", line 16, in init
self.load(bus)
File "/home/pi/workspaces/foos/foos/plugin_handler.py", line 24, in load
p = module.Plugin(bus)
File "/home/pi/workspaces/foos/plugins/io_raspberry.py", line 91, in init
self.goal_detector_black = GoalDetector(bus, self.goal_pin_black, "black")
File "/home/pi/workspaces/foos/plugins/io_raspberry.py", line 47, in init
GPIO.add_event_detect(self.pin, GPIO.FALLING, callback=self.on_goal, bouncetime=10)
RuntimeError: Failed to add edge detection

Hat jemand eine Idee woran das liegen kann ?

LG

**Comment by dpgoerlich** [comment]
Hi,

ich hab die GPIO Eingabe der Lichtschranken vorher per Script getestet. Da kommt definitiv das Signal an. Wo konfiguriere ich den Eindrahtbus? Kann aber eigentlich nicht sein, wenn mit simplen Script die Eingabe korrekt funktioniert oder ?

Wiringpi ist installiert. 

Betriebssystem ist Standard Raspbian Buster in der aktuellen Version.

LG

**Comment by dpgoerlich** [comment]
Hab mal eine neue Speicherkarte zur Hand genommen und es neu aufgesetzt, jetzt läuft es.
